name: update-readme
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 20 * * *' # 每天UTC时间晚上4点执行（北京时间24点）

jobs:
  README:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update top language
        run: |
          bash ./top_language.sh > README.md
